# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
  - go mod download

builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
  ldflags:
    - -s -w -X 'main.version={{ .Version }}'

archives:
- wrap_in_directory: true
  format: tar.gz

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
    - "eiladin/go-simple-startpage:{{ .Version }}"
    skip_push: true
    dockerfile: Dockerfile
    build_flag_templates:
    - "--build-arg version={{ .Version }}"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
