database:
  driver: "sqlite"
  dbname: "simple-startpage.db"
  username: "user"
  password: "pass"
  host: "localhost"
  port: "7890"

server:
  port: "3000"

healthCheck:
  timeout: "2000"

version: "1.0.2"