name: publish

on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2    
    - name: publish
      uses: docker/build-push-action@v1.1.0
      env:
        DOCKER_BUILDKIT: 1
      with:
        username: ${{ secrets.REPOSITORY_USERNAME }}
        password: ${{ secrets.REPOSITORY_PASSWORD }}
        repository: eiladin/go-simple-startpage
        build_args: version=${{github.ref}}
        tag_with_ref: true
        tag_with_sha: false
        add_git_labels: true
        push: true