name: test-pr

on:
  pull_request:
    branches: [ master ]  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Run test
      run: go test ./... -v -tags=test -coverprofile=coverage.out

    - name: convert gcov to lcov
      uses: jandelgado/gcov2lcov-action@v1.0.5
      with:
        infile: coverage.out
        outfile: coverage.lcov

    - name: coverage report
      uses: romeovs/lcov-reporter-action@v0.2.11
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: coverage.lcov